name: Build Android AAB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Ionic app
        run: npm run build

      - name: List www folder
        run: ls -la www/

      - name: Show index.html
        run: cat www/index.html

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK signé
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/vechlineconfigurator.jks
          cd android && ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$PWD/app/vechlineconfigurator.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VechlineConfigurator
          path: android/app/build/outputs/apk/release/app-release.apk